[project]
name = "hybrid-residual-grape"
version = "0.1.0"
description = "Hybrid physics-plus-RBF-residual GRAPE optimization from binary Fock-state measurements"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel",
    "jax",
    "jaxlib",
    "matplotlib",
    "numpy",
    "optax",
    "qutip",
    "scipy",
    "tqdm",
    "jax[cuda12]"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
